# Generated by Django 3.1.2 on 2020-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guest',
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_guest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=200),
        ),
    ]
