# Generated by Django 3.1 on 2020-11-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default=''),
        ),
    ]
