# Generated by Django 3.1.2 on 2020-11-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20201112_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='no_of_guest',
        ),
    ]
