# Generated by Django 3.1.2 on 2020-11-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_event_no_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='csvfile',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
