# Generated by Django 3.1.2 on 2020-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_event_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='csvfile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
