# Generated by Django 3.1.2 on 2020-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20201112_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='csvfile',
            field=models.FileField(upload_to='csvfile_for_guest/'),
        ),
    ]
