# Generated by Django 3.1.2 on 2020-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_auto_20201112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='csvfile',
            field=models.FileField(upload_to='csvfile_for_guest/<built-in function id>/'),
        ),
    ]
