# Generated by Django 3.1.3 on 2020-11-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20201112_2108'),
        ('Events', '0003_event_rules'),
    ]

    operations = [
    ]
